### ISSUE TITLE
Proposal: move delete button to detail page.

### ISSUE THREAD

**Issue by freekmurze** [spatie-custom/blender#145]
In general all lists in the backsite feature delete buttons on every single row. Although they are rarely used, all those buttons combined get quite some screen real estate.

Wouldn't it be better to move the detail button to the detail page of a model? Thoughts?

**Comment by willemvb** [comment]
I can imagine an author who wants to clean up his news section doesn't want to open every detail page and delete one by one.

Ideal situation:
- Batch actions on list view (select rows, select all, delete button) with a clean interface
- Individual delete on detail (maybe hidden under settings tab? This is probably not something you would use often while working on an article)

Option 1 requires some work though and sounds like Vue to me. Not sure if we want to replace the current dataTables and sortable tables setup?

**Comment by freekmurze** [comment]
> I can imagine an author who wants to clean up his news section doesn't want to open every detail page and delete one by one.

Show me one site where this has ever happened 😺 
For the vast majority of projects there is very little that ever gets deleted.

**Comment by sebastiandedeyne** [comment]
> Option 1 requires some work though and sounds like Vue to me. Not sure if we want to replace the current dataTables and sortable tables setup? 

I'd love to replace the dataTables but I don't want to write the replacement 🤓

**Comment by willemvb** [comment]
Me neither :). Ok, so we are not gonna replace dataTables for now.
Is it the styling of the red buttons that is too much? Maybe a more modest look is enough to tackle this (and eg. be more in line with the gray delete action of a media row). 
I still think list view is the logical place to delete items.

**Comment by freekmurze** [comment]
A more modest look would also be a great improvement
