### ISSUE TITLE
A module like fragments, but for images

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#167]
- Interface to upload images or collections with fragment-like names (e.g. `bureau.banner`)
- Easy way to define conversions per image collection

Maybe something for the intern?

**Comment by freekmurze** [comment]
Let's add media to fragments. A fragment can have multiple images. In the list view the fragments with images should be displayed separately. Let's just stick to defining conversions on a class (until we come across a project where we'd need to define let's say more than 5 different conversions).

**Comment by freekmurze** [comment]
Done
