### ISSUE TITLE
Preview offline content as admin

### ISSUE THREAD

**Issue by willemvb** [spatie-custom/blender#176]
Consider a pragmatic way to preview offline content (drafts etc) as admin.

**Comment by sebastiandedeyne** [comment]
Proposal:

- Disable the `online` check when there's an admin logged in and the url has a `?preview` query
- Manually add "Preview" buttons in Blender where relevant (module forms, maybe an icon on indexes, maybe combine the icon with online/offline status?)

**Comment by willemvb** [comment]
1. Sounds good
2. Combining with offline/online icon seems logical, will need to find a way to keep this clean in list view
