### ISSUE TITLE
Replace text with content in articles

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#178]
I still want to be able to divide my articles in blocks (as in sections)!

## Proposal

- Drop `text`
- Add `content`, which stores a translatable json file
- Overwrite `__get` to include `content`

## Examples

An article with `content` `{"nl":{"text":""}}` would behave exactly the same as an article in it's current form.

```php
echo $article->text;
```

An article with `content` `{"nl":{"text":"","intro":""}}` would also have an `intro` attribute.

```php
echo $article->text;
echo $article->intro;
```

**Comment by freekmurze** [comment]
Show me some real life examples next week to convince me for the need of this change.

**Comment by sebastiandedeyne** [comment]
Closing until necessary.
