### ISSUE TITLE
Browserify Failed!: Cannot find module 'blender-media'

### ISSUE THREAD

**Issue by liucf** [spatie-custom/blender#18]
when i run gulp --back,  have Browserify Failed!: Cannot find module 'blender-media'  this error.

dig into the code, i found the issue is in  resource/assets/js/back/app.js, last line code is 
require('./media')

if i comment out this line, they run gulp --back, it works without the error.
so looks like missed some file? how can i fix it?

thanks

**Comment by sebastiandedeyne** [comment]
It could be that you're missing a package which should be installed via our private npm repository. You can set it up via these commands:

``` bash
npm set registry https://npm.spatie.be
npm set ca null
```

Our registry is set up with Sinopia: https://github.com/rlidwka/sinopia

Don't forget to remove the registry line from your ~/.npmrc if you're planning to publish to npm at some point!

If it's a different issue, feel free to post the error up here and I'll check it out.

**Comment by liucf** [comment]
still not working...
and i do see i already have a folder named "blender-media" under node_modules folder.
so i should have that package already?

thanks

**Comment by sebastiandedeyne** [comment]
Completely deleting `node_modules` after setting up the registry might be necessary.

And what branch of this project are you trying to install?

**Comment by liucf** [comment]
@sebastiandedeyne 
hmm, sitll not working. is there any install guide for this project?

thanks

**Comment by sebastiandedeyne** [comment]
Sorry, currently no install guide for this project, can't promise it anytime soon either.

Maybe it's not working with your NPM version, the project currently requires v3+.

If you need any more help, please paste the entire error here, and let me know the branch, or even better the commit hash, of Blender.

**Comment by willemvb** [comment]
We've added an install section to the readme.
