### ISSUE TITLE
Advantage of enums

### ISSUE THREAD

**Issue by panovskidejan** [spatie-custom/blender#19]
What is the advantage of defining the roles as enums instead as array as below

``` php
public static function getRoles()
{
    return [
        'ADMIN' => 'admin',
        'MEMBER' => 'member'
    ];
}
```

**Comment by freekmurze** [comment]
From the readme of the [enum package](https://github.com/myclabs/php-enum):

> Using an enum instead of class constants provides the following advantages:
> - You can type-hint: `function setAction(Action $action) {`
> - You can enrich the enum with methods (e.g. `format`, `parse`, …)
> - You can extend the enum to add new values (make your enum `final` to prevent it)
> - You can get a list of all the possible values (see below)

Though typehinting of enums is not being used in Blender atm, we plan on doing so in the future.
