### ISSUE TITLE
Sass Compilation Failed

### ISSUE THREAD

**Issue by XavRsl** [spatie-custom/blender#20]
Hi !
I'm trying to install blender on my homestead box. I went through all the installation steps and always run into this error :

```
[10:24:55] gulp-notify: [Laravel Elixir] Sass Compilation Failed: resources/assets/sass/back/back.scss
Error: file to import not found or unreadable: datatables/media/css/jquery.dataTables
       Current dir:
        on line 7 of stdin
>> @import 'datatables/media/css/jquery.dataTables';
   --------^

{ [Error: resources/assets/sass/back/back.scss
Error: file to import not found or unreadable: datatables/media/css/jquery.dataTables
       Current dir:
        on line 7 of stdin
>> @import 'datatables/media/css/jquery.dataTables';
   --------^
]
```

I've tried it a few times before posting this issue. Seems like datatables module is installed by the blender.js package but sass doesn't seem to have access to it. Any idea ?

Thanks.

Xavier

**Comment by sebastiandedeyne** [comment]
Are you by chance using an NPM version below v3? The sass imports expect a flat directory structure in `node_modules`.

**Comment by XavRsl** [comment]
Hi !
Good call ! I was not aware of the fact that `npm upgrade` only upgrades the current main version. 
As a reminder, after installing the lastest version of nodejs, here's the command to upgrade npm :

```
sudo npm install npm -g
```

It's working now !

I'm closing the issue. Thanks !!!!!

Xavier

**Comment by freekmurze** [comment]
Out of curiosity: are you trying out Blender for fun or are you planning to use it on a real project?

**Comment by XavRsl** [comment]
Neither... I'm building a website for a client and I'm in the process of looking around for the best practices. I'll probably use some pieces of your project that I would find useful. And there are a few !
