### ISSUE TITLE
Replace the translatable package with vinkla's

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#22]
https://github.com/vinkla/translator

Because using traits is cooler than inheritance.

**Comment by sebastiandedeyne** [comment]
Unfortunately way more complex than anticipated, so on hold for now.

**Comment by freekmurze** [comment]
![switch](https://cloud.githubusercontent.com/assets/483853/11210510/edf175c2-8d28-11e5-9333-2c7d91e1a992.png)

**Comment by sebastiandedeyne** [comment]
Got our own one now!
