### ISSUE TITLE
where is htaccess file ?

### ISSUE THREAD

**Issue by ghost** [spatie-custom/blender#242]

**Comment by freekmurze** [comment]
We don't need that file as we're using nginx

**Comment by ghost** [comment]
ok but you could tell me to create an .htaccess file and put in public folder instead of closing this issuee

**Comment by sebastiandedeyne** [comment]
@DeeJaVu Please note that we don't provide support on this repository, as per the readme:

> You may use our template but please notice that we offer no support whatsoever. We also don't follow semver for this project and won't guarantee that the code (especially the master branch) is stable. In short: when using this, you're on your own.

The reason why we didn't provide a clearer answer on the htaccess issue, is because it's not our area of expertise and we could be spreading false information.

**Comment by ghost** [comment]
@sebastiandedeyne Thank you for pointing that out
