### ISSUE TITLE
Error composer installer

### ISSUE THREAD

**Issue by brecky** [spatie-custom/blender#245]
git clone this repo 
run composer install 

[Symfony\Component\Debug\Exception\FatalThrowableError]
  Parse error: syntax error, unexpected '='

**Comment by sebastiandedeyne** [comment]
Blender requires PHP 7.1+, are you running the latest version of PHP?

**Comment by brecky** [comment]
sorry my php 7.0.13  
use XAMPP Windows 10
PHPStorm

Ubuntu 16.04 LTS use Php 7.0.8 
Upgrade !!

**Comment by sebastiandedeyne** [comment]
You'll need to upgrade to PHP7.1 to run this project.

Downloading the latest version of XAMPP should do the trick! https://www.apachefriends.org/download.html
