### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by brecky** [spatie-custom/blender#246]
C:\xampp\htdocs\blender>npm install
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\brecky\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 no such package available : @spatie/blender-css
npm ERR! 404
npm ERR! 404  '@spatie/blender-css' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'Blender'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

C:\xampp\htdocs\blender>npm set registry http://npm.spatie.be

C:\xampp\htdocs\blender>npm set ca null

C:\xampp\htdocs\blender>npm install
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code E404

npm ERR! 404 no such package available : @spatie/scss
npm ERR! 404
npm ERR! 404  '@spatie/scss' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'Blender'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by sebastiandedeyne** [comment]
Does it work if you use `yarn` instead?

https://yarnpkg.com

**Comment by brecky** [comment]
[npm install -g  vue@^2.1.0 webpack@^2.2.0 node-sass@^4.0.0 laravel-elixir-vue-2](url)
gulp error again
 Working directory changed to C:\xampp\htdocs
module.js:472
    throw err;
    ^

Error: Cannot find module 'laravel-elixir-vue-2'
    at Function.Module._resolveFilename (module.js:470:15)

`npm run dev`

"C:\Program Files (x86)\JetBrains\PhpStorm 2016.3.2\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\Users\tibor\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js run dev


> Blender@ dev C:\xampp\htdocs\blender
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
   ```
 Asset       Size  Chunks                    Chunk Names
js/back.blocks-15858c940d5303a912c0.js    1.02 MB       0  [emitted]  [big]  back.blocks
 js/back.media-0ba55a0c2e15edb0ed77.js     915 kB       1  [emitted]  [big]  back.media
 js/back.chart-68c4f1cb7d9251e65073.js     122 kB       2  [emitted]         back.chart
  /js/back.app.cf9f5a2bc877f717f498.js    1.41 MB       3  [emitted]  [big]  /js/back.app
 /js/front.app.4bbb9e6ed591da012e93.js     589 kB       4  [emitted]  [big]  /js/front.app
/js/front.head.fa7bae7f4fa3dbfa220c.js    46.2 kB       5  [emitted]         /js/front.head
 /js/back.head.dbc2e5a6d677c5a48991.js    45.9 kB       6  [emitted]         /js/back.head
   /css/front.27f99908d4c32f52bdc5.css    33.8 kB       5  [emitted]         /js/front.head
    /css/back.27f99908d4c32f52bdc5.css     168 kB       5  [emitted]         /js/front.head
                     mix-manifest.json  624 bytes          [emitted]         
```
Its OK

**Comment by brecky** [comment]
Front working 
Back (admin ) don`t working
Login fail

**Comment by freekmurze** [comment]
Did you run the migrations / seeders?

**Comment by sebastiandedeyne** [comment]
Closing this for now. Feel free to reopen if you're still having issues.
