### ISSUE TITLE
error when run gulp

### ISSUE THREAD

**Issue by hrmsandi** [spatie-custom/blender#25]
hello,

when i run gulp, i get Error: spawn webpack ENOENT, how can i fix it?

**Comment by sebastiandedeyne** [comment]
You'll need to have webpack installed globally to run gulp.

```
npm install -g webpack
```

**Comment by hrmsandi** [comment]
doesn't work :(

**Comment by sebastiandedeyne** [comment]
Hmm, let's see;
- What NPM version are you on? (v3+ is required)
- Is Webpack definitely available in your path? (if you type `which webpack`, you get it's location)

**Comment by hrmsandi** [comment]
my NPM version is 3.7.3 and webpack path is /cygdrive/c/Users/shandy05/AppData/Roaming/npm/webpack

**Comment by sebastiandedeyne** [comment]
I'd say dive in to `node_modules/blender-gulp/tasks/webpack.js` and try to replace the `webpack` command that's in the `spawn` call with your full path.

I don't know what the correct solution would be since I'm not really experienced in debugging in windows environments.

**Comment by hrmsandi** [comment]
i try to reinstall from homestead ssh, and this work, I think the problem is the nodejs in windows.

thank you sebastiandedeyne.
