### ISSUE TITLE
elixir configuration

### ISSUE THREAD

**Issue by dehboris** [spatie-custom/blender#26]
I do not see the configuration of elixir.
I just see in gulpfile.js
`require('blender-gulp');
`

**Comment by sebastiandedeyne** [comment]
We're not using elixir anymore in favor of webpack, we use our own gulp boilerplate, and have per-project configuration in the `webpack.config.js` file.

blender-gulp (the readme is outdated though): https://github.com/spatie-custom/blender-gulp
More on the transition to webpack: https://sebastiandedeyne.com/posts/2016/adventure-time-with-webpack
