### ISSUE TITLE
Error when I run gulp

### ISSUE THREAD

**Issue by neowill2013** [spatie-custom/blender#33]
[12:47:09] Using gulpfile ~/code/blendup/gulpfile.js
[12:47:09] Starting 'default'...
[12:47:09] Starting 'webpack'...
[12:47:09] Starting 'svg'...
[12:47:10] Finished 'svg' after 915 ms
Hash: c1175115de18d3b5b80f
Version: webpack 2.1.0-beta.2
Time: 97818ms
              Asset       Size  Chunks             Chunk Names
      back.media.js    1.32 MB       0  [emitted]  back.media
      front.head.js    45.1 kB       1  [emitted]  front.head
       front.app.js     340 kB       2  [emitted]  front.app
front.validation.js    42.9 kB       3  [emitted]  front.validation
      back.chart.js     126 kB       4  [emitted]  back.chart
     back.vendor.js     271 kB       5  [emitted]  back.vendor
     back.editor.js    3.05 kB       6  [emitted]  back.editor
       back.head.js    46.6 kB       7  [emitted]  back.head
        back.app.js    1.25 MB       8  [emitted]  back.app
  rev-manifest.json  334 bytes          [emitted]
  [86] multi back.vendor 28 bytes {5} [built]
    + 345 hidden modules
## this is the error

> ERROR in Entry module not found: Error: Can't resolve 'style' in '/home/vagrant/code/blendup/resources/assets'
> 
> ERROR in Entry module not found: Error: Can't resolve 'style' in '/home/vagrant/code/blendup/resources/assets'
> 
> ERROR in ./js/back/modules/editor.js
> Module not found: Error: Can't resolve '../redactor/langs/nl.js' in '/home/vagrant/code/blendup/resources/assets/js/back/modules'
>  @ ./js/back/modules/editor.js 12:0-34
> 
> ERROR in ./js/back/modules/editor.js
> Module not found: Error: Can't resolve '../redactor/redactor/redactor.js' in '/home/vagrant/code/blendup/resources/assets/js/back/modules'
>  @ ./js/back/modules/editor.js 10:0-43
> 
> ERROR in ./js/back/modules/editor.js
> Module not found: Error: Can't resolve '../redactor/plugins/imagemanager.js' in '/home/vagrant/code/blendup/resources/assets/js/back/modules'
>  @ ./js/back/modules/editor.js 14:0-46
> 
> ERROR in ./js/back/modules/editor.js
> Module not found: Error: Can't resolve '../redactor/plugins/video.js' in '/home/vagrant/code/blendup/resources/assets/js/back/modules'
>  @ ./js/back/modules/editor.js 16:0-39
> [12:48:51] Finished 'webpack' after 1.68 min

**Comment by willemvb** [comment]
We are using Redactor from Imperavi in our projects, but don't have the license to open source this part.
You will have to remove following code

```
if ($('[data-editor]').size()) {
    require.ensure([], () => { require('./modules/editor').default(); }, 'back.editor');
}
```

in `resources/assets/back/app.js` to run Gulp.

I'll update the Readme accordingly.

**Comment by neowill2013** [comment]
Still I'm getting this error:

> ERROR in Entry module not found: Error: Can't resolve 'style' in '/home/vagrant/code/blendup/resources/assets'
> 
> ERROR in Entry module not found: Error: Can't resolve 'style' in '/home/vagrant/code/blendup/resources/assets'

**Comment by willemvb** [comment]
I'm not 100% sure, but our guess is that this has to do with your webpack version `2.1.0-beta.2`. 
We are using `^1.12.11` in our `blender-gulp` package.
Unfortunately no plans yet to update this.

**Comment by neowill2013** [comment]
Tried it but still not fixed.

**Comment by willemvb** [comment]
Could you run `webpack --display-error-details` and send us the output?

**Comment by neowill2013** [comment]
### vagrant@homestead:~/code/blendup$ gulp
[09:25:17] Using gulpfile ~/code/blendup/gulpfile.js
[09:25:17] Starting 'default'...
[09:25:17] Starting 'webpack'...
[09:25:17] Starting 'svg'...
[09:25:20] Finished 'svg' after 3.43 s
Hash: 41be69332f3e155b3246
Version: webpack 1.13.0
Time: 85930ms
              Asset       Size  Chunks             Chunk Names
        back.app.js    1.25 MB       0  [emitted]  back.app
      back.chart.js     126 kB       1  [emitted]  back.chart
      back.media.js    1.32 MB       2  [emitted]  back.media
       back.head.js    46.5 kB       3  [emitted]  back.head
     back.vendor.js     271 kB       4  [emitted]  back.vendor
       front.app.js     340 kB       5  [emitted]  front.app
front.validation.js    42.9 kB       6  [emitted]  front.validation
      front.head.js      45 kB       7  [emitted]  front.head
  rev-manifest.json  296 bytes          [emitted]
   [0] multi back.vendor 28 bytes {4} [built]
    + 344 hidden modules

> ERROR in Entry module not found: Error: Cannot resolve module 'style' in /home/vagrant/code/blendup/resources/assets
> 
> ERROR in Entry module not found: Error: Cannot resolve module 'style' in /home/vagrant/code/blendup/resources/assets

[09:26:54] Finished 'webpack' after 1.6 min


### vagrant@homestead:~/code/blendup$ webpack --display-error-details
Hash: 41be69332f3e155b3246
Version: webpack 1.13.0
Time: 53471ms
              Asset       Size  Chunks             Chunk Names
        back.app.js    1.25 MB       0  [emitted]  back.app
      back.chart.js     126 kB       1  [emitted]  back.chart
      back.media.js    1.32 MB       2  [emitted]  back.media
       back.head.js    46.5 kB       3  [emitted]  back.head
     back.vendor.js     271 kB       4  [emitted]  back.vendor
       front.app.js     340 kB       5  [emitted]  front.app
front.validation.js    42.9 kB       6  [emitted]  front.validation
      front.head.js      45 kB       7  [emitted]  front.head
  rev-manifest.json  296 bytes          [emitted]
   [0] multi back.vendor 28 bytes {4} [built]
    + 344 hidden modules

ERROR in Entry module not found: Error: Cannot resolve module 'style' in /home/vagrant/code/blendup/resources/assets
resolve module style in /home/vagrant/code/blendup/resources/assets
  looking for modules in /home/vagrant/code/blendup/node_modules
    module variation style-webpack-loader
      /home/vagrant/code/blendup/node_modules/style-webpack-loader doesn't exist (module as directory)
      resolve 'file' style-webpack-loader in /home/vagrant/code/blendup/node_modules
        resolve file
          /home/vagrant/code/blendup/node_modules/style-webpack-loader doesn't exist
          /home/vagrant/code/blendup/node_modules/style-webpack-loader.webpack-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-webpack-loader.web-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-webpack-loader.loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-webpack-loader.js doesn't exist
    module variation style-web-loader
      /home/vagrant/code/blendup/node_modules/style-web-loader doesn't exist (module as directory)
      resolve 'file' style-web-loader in /home/vagrant/code/blendup/node_modules
        resolve file
          /home/vagrant/code/blendup/node_modules/style-web-loader doesn't exist
          /home/vagrant/code/blendup/node_modules/style-web-loader.webpack-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-web-loader.loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-web-loader.web-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-web-loader.js doesn't exist
    module variation style-loader
      /home/vagrant/code/blendup/node_modules/style-loader doesn't exist (module as directory)
      resolve 'file' style-loader in /home/vagrant/code/blendup/node_modules
        resolve file
          /home/vagrant/code/blendup/node_modules/style-loader doesn't exist
          /home/vagrant/code/blendup/node_modules/style-loader.webpack-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-loader.web-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-loader.loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-loader.js doesn't exist
    module variation style
      /home/vagrant/code/blendup/node_modules/style doesn't exist (module as directory)
      resolve 'file' style in /home/vagrant/code/blendup/node_modules
        resolve file
          /home/vagrant/code/blendup/node_modules/style doesn't exist
          /home/vagrant/code/blendup/node_modules/style.webpack-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style.web-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style.loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style.js doesn't exist

ERROR in Entry module not found: Error: Cannot resolve module 'style' in /home/vagrant/code/blendup/resources/assets
resolve module style in /home/vagrant/code/blendup/resources/assets
  looking for modules in /home/vagrant/code/blendup/node_modules
    module variation style-webpack-loader
      /home/vagrant/code/blendup/node_modules/style-webpack-loader doesn't exist (module as directory)
      resolve 'file' style-webpack-loader in /home/vagrant/code/blendup/node_modules
        resolve file
          /home/vagrant/code/blendup/node_modules/style-webpack-loader doesn't exist
          /home/vagrant/code/blendup/node_modules/style-webpack-loader.webpack-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-webpack-loader.web-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-webpack-loader.loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-webpack-loader.js doesn't exist
    module variation style-web-loader
      /home/vagrant/code/blendup/node_modules/style-web-loader doesn't exist (module as directory)
      resolve 'file' style-web-loader in /home/vagrant/code/blendup/node_modules
        resolve file
          /home/vagrant/code/blendup/node_modules/style-web-loader doesn't exist
          /home/vagrant/code/blendup/node_modules/style-web-loader.webpack-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-web-loader.loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-web-loader.web-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-web-loader.js doesn't exist
    module variation style-loader
      /home/vagrant/code/blendup/node_modules/style-loader doesn't exist (module as directory)
      resolve 'file' style-loader in /home/vagrant/code/blendup/node_modules
        resolve file
          /home/vagrant/code/blendup/node_modules/style-loader doesn't exist
          /home/vagrant/code/blendup/node_modules/style-loader.webpack-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-loader.web-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-loader.loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style-loader.js doesn't exist
    module variation style
      /home/vagrant/code/blendup/node_modules/style doesn't exist (module as directory)
      resolve 'file' style in /home/vagrant/code/blendup/node_modules
        resolve file
          /home/vagrant/code/blendup/node_modules/style doesn't exist
          /home/vagrant/code/blendup/node_modules/style.webpack-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style.web-loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style.loader.js doesn't exist
          /home/vagrant/code/blendup/node_modules/style.js doesn't exist

**Comment by willemvb** [comment]
It seems like the problem has to do with the npm module `style-loader` which should have been installed alongside `blender-gulp`. Didn't you get errors during `npm install`?
What is your output of `npm list style-loader`?

```
Blender@5.4.2
└─┬ blender-gulp@2.0.6
  └── style-loader@0.13.1
```

You could try to install `style-loader` manually by running `npm i style-loader` or just remove the entire `node_modules` folder and run `npm i` again.

**Comment by neowill2013** [comment]
will send you soon. Currenlty lost my all data due to formatting. Will get back soon.

**Comment by sebastiandedeyne** [comment]
We actually encountered this error yesterday, and it was due to an older NPM version (webpack breaks below v3 here, since the `node_modules` directory needs to be flattened).
