### ISSUE TITLE
Wrong config file reference in PrefetchAnalyticsData

### ISSUE THREAD

**Issue by pixelpeter** [spatie-custom/blender#364]
In `App\Console\Command\PrefetchAnalyticsData` in line `34` you reference the config file for the `laravel-analytics`package as 
```
...
if (empty(config('laravel-analytics.view_id'))) {
...
```

To get it working I need to change it to:
```
...
if (empty(config('analytics.view_id'))) {
...
```

**Comment by freekmurze** [comment]
Fixed, thanks for letting us know.
