### ISSUE TITLE
There is no 'AppServiceProvider.php' file in path of 'app/Providers',why?

### ISSUE THREAD

**Issue by JKChen** [spatie-custom/blender#366]
I found that there is no 'AppServiceProvider.php' file in path of 'app/Providers'.
How can i modify the boot method of 'AppServiceProvider.php' file?

**Comment by sebastiandedeyne** [comment]
Depending on what you want to accomplish, you can create a new service with `php artisan make:provider`.

The default `AppServiceProvider` is a bit too generic for our taste, we prefer to split the services of our app in multiple providers.

**Comment by JKChen** [comment]
Thank you for your reply. I created the file for my personal purpose.
