### ISSUE TITLE
Seeding error when run ‘php artisan migrate --seed’

### ISSUE THREAD

**Issue by JKChen** [spatie-custom/blender#367]
```
Migrating: 2016_11_09_154021_create_content_blocks_table
Migrated:  2016_11_09_154021_create_content_blocks_table
Seeding: BackUserSeeder
Seeding: FrontUserSeeder
Seeding: FragmentSeeder
Seeding: TagSeeder
Seeding: ArticleSeeder
'"jpegtran"' is not recognized as an internal or external command,operable program or batch file.
'"jpegtran"' is not recognized as an internal or external command,operable program or batch file.
```
Looks like some packages are missing, like "jpegtran" or other names.

**Comment by freekmurze** [comment]
You should install those yourself

**Comment by JKChen** [comment]
Yes. When I run
`npm install --global jpegtran-bin`
before
`php artisan migrate --seed`
then all tables are seeded successfully.

**Comment by freekmurze** [comment]
Note that we'll swap out the current image optimizer soon by our own one.

https://github.com/spatie/image-optimizer

This new package will make installing optimization tools optional. It will just skip image optimization if the need binaries are not present on your system.

**Comment by JKChen** [comment]
Cool~
