### ISSUE TITLE
Refactor auth module

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#376]
To discuss when we have some time for updating Blender...

**Comment by sebastiandedeyne** [comment]
Rename user models to `User` and `Administrator`

**Comment by sebastiandedeyne** [comment]
Maybe change default passwords to `secret` instead of first names, to be in sync with what Laravel does.

**Comment by ianrodrigues** [comment]
Hi there,

I'd like to do this task, 😁. Is there something more about this topic to discuss?

**Comment by sebastiandedeyne** [comment]
Nice!

So the goal here is to simplify things. Here are the main tasks at hand. If it's a bit more than you expected, feel free to do parts of it 😄 

- Rename `FrontUser` to `User`
- Rename `BackUser` to `Administrator`
- Move these to the `app/models` directory
- Remove the enum objects, and replace them with class constants
- Rename the associated presenters, and move them to `app/models/presenters`
- Move the mail classes to `app/mails`, and update the namespaces where they're used

That's all I can think of for now. Gonna remove some of the model functions that we rarely use too to keep things lightweight, but I'll go through those afterwards.

**Comment by ianrodrigues** [comment]
Great, sounds good for me.
