### ISSUE TITLE
Nuke app/Http/Requests

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#393]
I don't really like these anymore. Yay / nay?

**Comment by AlexVanderbist** [comment]
Yay, the `ValidatesRequests` trait and policies are often a better solution imo

**Comment by freekmurze** [comment]
Yay, doing validation in the controllers seems like the way to go.

**Comment by freekmurze** [comment]
Boom, it's gone.

**Comment by sebastiandedeyne** [comment]
❤️
