### ISSUE TITLE
Hardcoded button text 

### ISSUE THREAD

**Issue by StefanNeuser** [spatie-custom/blender#494]
Within Content-Blocks:

<img width="314" alt="screen shot 2018-01-10 at 12 03 46" src="https://user-images.githubusercontent.com/2176503/34769553-69b4716a-f5fe-11e7-8e0f-d22bddbca4d4.png">

Please replace with fractal/translation.

Thank you

**Comment by sebastiandedeyne** [comment]
See https://github.com/spatie/blender-content-blocks/issues/3
