### ISSUE TITLE
Provide a better error message when Slack hook is not filled in .env file

### ISSUE THREAD

**Issue by freekmurze** [spatie-custom/blender#497]
Right now it fails with a non-descriptive message

```
[Httpful\Exception\ConnectionErrorException]
  Unable to connect to "": 3 <url> malformed
```

Let's manually detect if the right env variable is set and, if not, fail with more informative error message.

**Comment by sebastiandedeyne** [comment]
Or drop Slack hooks alltogether 🙈

**Comment by freekmurze** [comment]
This has already been dropped! 🎉
