### ISSUE TITLE
Subject of PasswordReset Mail not working and missing translation

### ISSUE THREAD

**Issue by StefanNeuser** [spatie-custom/blender#511]
Hi Spatie Team,

no big issue but it seems that setting the subject is not working. Ok it is in the app folder, so everyone is able to edit it but maybe a translation call is also a good choice.

https://github.com/spatie/blender/blob/e07935806bf61d63d9baf93c6cffa972426a6e04/app/Mail/EventHandler.php#L30

-Stefan

**Comment by TVke** [comment]
Hi @StefanNeuser 

The password reset mail is controlled in the `ResetPassword` class located at `app/Services/Auth/Front/Mail/ResetPassword.php`

Hope this helps.
