### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Sogl** [spatie-custom/blender#533]
Ok, I spent 2 days just to build yarn packages because of `node-gyp` errors...

Now I see 1st page, but...
![image](https://user-images.githubusercontent.com/7556290/59608394-ef841280-911d-11e9-84b3-d4c6eb6153ee.png)

Where is articles and news?
Where is backeng login?

How to use this boilerplate? 😺 

I saw routes in php files, but all of them return me
![image](https://user-images.githubusercontent.com/7556290/59608460-0b87b400-911e-11e9-8a96-ac28a366a6aa.png)

What I'm doing wrong?

**Comment by freekmurze** [comment]
I'm sorry, we don't support this anymore.

**Comment by Sogl** [comment]
So sad. Not so much really good Laravel/Vue CMS boilerplates.

Anyway I solved some of my questions and can dig in blender code by myself. Thanks for your work.
