### ISSUE TITLE
ActivitylogFacade referenced in config/app.php - non-existant file

### ISSUE THREAD

**Issue by madsem** [spatie-custom/blender#534]
You removed the ActivitylogFacade in commit #https://github.com/spatie/laravel-activitylog/commit/869ac884e352ece2bf22d39d9096d8c2ba581fdc but it's still referenced in Blender's app.php https://github.com/spatie/blender/blob/6af1940c03b523ae0834fd4b3915203f2bc10e58/config/app.php#L275

**Comment by freekmurze** [comment]
We really don’t use this repo anymore. I’ll archive it.

**Comment by madsem** [comment]
alright, sorry, seemed to be in active development with latest commit from febr. :)
