### ISSUE TITLE
Fragment improvements

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#6]
## Fragments yaml
- [x] Move all non Laravel core `lang` file contents to fragments
## Backend
- [x] Add artisan command to seed fragments
## Front usage improvements
- [x] Variable support
## Admin view improvements
- [ ] Add structure to the fragments index (by the first key in it's name?)
- [ ] Flag for non-translatable fragments (would still be a translatable in the database)

**Comment by freekmurze** [comment]
Checked some boxes

**Comment by freekmurze** [comment]
We'll figure out a new workflow for fragments in the Blender's Winter 2017 refresh.
