### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#7]
Provide a clean way to set page titles.
## Goals
- [ ] Don't clutter views
- [ ] Automatically append site name

**Comment by sebastiandedeyne** [comment]
Maybe combine with #3?

**Comment by willemvb** [comment]
Possibly look for a way to administer even more meta data for a page, eg. page description, og:tags etc. ?

**Comment by sebastiandedeyne** [comment]
Maybe an SEO module in Blender similar to fragments (for titles, url's, meta & og tags)

Related: would be nice to save this in a json/yaml file for easier routes & navigation generation /cc @freekmurze
