### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#76]
Multiple issues, random thoughts:
- Tags being defined as an n:m has a major issue: It can kill a site if a tag is deleted that a model depends on. Cascading would be too destructive too since it could potentially delete a lot of models
- Lot's of the tag type code just doesn't feel good. I'd prefer to get rid of type, and having some sort of extendable tag model so we can create one per type, it's not like we need dynamic types anyway
- Would be nice to have this in it's own repo (either under spatie or spatie-custom)

**Comment by freekmurze** [comment]
We'll move tag functionality to it's own public package. It has to be extensible so we can add translations to it in our own projects.
