### ISSUE TITLE
Kill Foundation?

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender#78]
Foundation pretty much never changes on a per-project basis. Would be better to move this to one or multiple packages.
- [x] `spatie/enum`
- [x] `spatie-custom/blender-model` (maybe move `ModuleModelController` there too?)
- [x] `spatie/laravel-tags` or `spatie-custom/blender-tags`

If a project really needs an override, we can just copy the code from the package. I'm not afraid of this situation since I don't think I've ever had to do this, so it would be an edge case.

**Comment by freekmurze** [comment]
Let's do this!

**Comment by freekmurze** [comment]
Done
